package com.dao;

import com.entity.Team;
import com.entity.TeamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeamMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbggenerated  Tue Jun 12 14:57:18 CST 2018
	 */
	int countByExample(TeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbggenerated  Tue Jun 12 14:57:18 CST 2018
	 */
	int deleteByExample(TeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbggenerated  Tue Jun 12 14:57:18 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbggenerated  Tue Jun 12 14:57:18 CST 2018
	 */
	int insert(Team record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbggenerated  Tue Jun 12 14:57:18 CST 2018
	 */
	int insertSelective(Team record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbggenerated  Tue Jun 12 14:57:18 CST 2018
	 */
	List<Team> selectByExample(TeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbggenerated  Tue Jun 12 14:57:18 CST 2018
	 */
	Team selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbggenerated  Tue Jun 12 14:57:18 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Team record,
			@Param("example") TeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbggenerated  Tue Jun 12 14:57:18 CST 2018
	 */
	int updateByExample(@Param("record") Team record,
			@Param("example") TeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbggenerated  Tue Jun 12 14:57:18 CST 2018
	 */
	int updateByPrimaryKeySelective(Team record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbggenerated  Tue Jun 12 14:57:18 CST 2018
	 */
	int updateByPrimaryKey(Team record);
}